### ISSUE TITLE
No save file created on Linux (Flatpak) CloudCompare version 2.11.0

### ISSUE THREAD

**Issue by chippey** [flathub/org.cloudcompare.CloudCompare#21] opened 2022-08-10 20:29 UTC
Cross reporting over to here since the CC project doesn't maintain the flatpak build.  To summarize, saving or otherwise writing files doesn't work with the flatpak build, even when write permissions are enabled:
https://github.com/CloudCompare/CloudCompare/issues/1460

**Comment by christian-rauch** [comment] 2022-08-10 21:05
Loading and saving works for me:

1. download PLY file from https://people.sc.fsu.edu/~jburkardt/data/ply/airplane.ply
2. drag & drop the PLY into Cloud Compare
3. click on `Mesh` in the `DB Tree` so that the mesh is highlighted with a bounding box
4. press <kbd>Ctrl</kbd>+<kbd>S</kbd> to save (or use the file menu) ... a file Portal dialog will open
5. chose a location and file name and save

This creates the file as expected in the chosen location.

Can you share steps to reproduce this or a video that shows the issue?

**Comment by chippey** [comment] 2022-08-10 21:35
I repeated your steps, but get no created file.  See also the linked thread above for additional reports.

**Comment by chippey** [comment] 2022-08-10 22:16
Video showing the issue.
![Peek 2022-08-10 17-14](https://user-images.githubusercontent.com/3241883/184029973-386c36bf-e5bb-448c-b594-7ae321c59018.gif)

**Comment by chippey** [comment] 2023-04-01 16:27
Just noting this is still an issue, and is definitely a flatpak build problem.  Compiled the same version from source saves files fine.  This is a somewhat big problem since flatpak is the only way listed to download and install on the CloudCompare website, as no .rpm or .deb files are published.

**Comment by christian-rauch** [comment] 2023-04-01 16:38
> This is a somewhat big problem since flatpak is the only way listed to download and install on the CloudCompare website

How big of a problem is this? I still cannot reproduce your issue on Ubuntu 22.04 with the steps I listed in https://github.com/flathub/org.cloudcompare.CloudCompare/issues/21#issuecomment-1211272250.

You demonstrate the issue on your side on KDE. I assume that you are using the `xdg-desktop-portal-kde`? Can you reproduce this on GNOME with the `xdg-desktop-portal-gnome`? Is this maybe an issue with the KDE portal and not Flatpak?

**Comment by chippey** [comment] 2023-04-01 17:15
Looks like `xdg-desktop-portal-kde` is the default with KDE, and that's what's being used.  It's odd, as the only other flatpak distributed software we have installed (AlphaPlot) saves files fine.  I'll try spinning up a GNOME install when I get home.

I realize you're just yourself maintaining the packaging for CC on the Linux side, and for that I'm thankful.  The problem comes from that this is the only 'blessed' distribution of CC when trying to deploy it in our lab, and then it doesn't work in our environment.  Trying to deploy based on source significantly complicates things.

**Comment by christian-rauch** [comment] 2023-04-01 19:51
> I realize you're just yourself maintaining the packaging for CC on the Linux side, and for that I'm thankful.

I created and maintain this flatpak in my free time and I am not affiliated with any of the projects involved (flatpak, the portals or CloudCompare). I don't have the capacity to support all edge cases or debug the entire stack that makes the flatpaks run. I rely on others to report issues and provide reproducible examples with details of their setup.

> The problem comes from that this is the only 'blessed' distribution of CC when trying to deploy it in our lab, and then it doesn't work in our environment.

What is your lab setup? If it is using any recent Linux distribution, can you not use GNOME?

**Comment by chippey** [comment] 2023-04-01 20:29
> I created and maintain this flatpak in my free time and I am not affiliated with any of the projects involved (flatpak, the portals or CloudCompare). I don't have the capacity to support all edge cases or debug the entire stack that makes the flatpaks run. I rely on others to report issues and provide reproducible examples with details of their setup.

I realize that, hence being thankful to you that there's any Linux packaging at all.  From the end-user perspective, it does become a pinch-point when your flatpak is the only and featured Linux distribution of CloudCompare on the official ClouldCompare website.  This is not a you problem, but it is a source of frustration when things go wrong.

> What is your lab setup? If it is using any recent Linux distribution, can you not use GNOME?

Ubuntu 20.04 LTS with KDE.  KDE is the preferred DE.

I think the plan to go forward is to setup an internal .deb repository and only use source builds of CC.

**Comment by christian-rauch** [comment] 2023-04-01 22:28
I installed Fedora 37 with KDE and again could not reproduce the issue with the steps above:

https://user-images.githubusercontent.com/8226248/229316957-d142ceb4-9161-4e03-ac31-ab9254420931.mp4

The saved file `bla.ply` gets created as expected.

**Comment by christian-rauch** [comment] 2023-11-26 14:45
I am closing this as no further reports with this issue have been made and new releases happened since this was reported. Reopen this issue if you have more information an steps that can reproduce the issue.

**Closed by christian-rauch** 2023-11-26 14:45 UTC
